### ISSUE TITLE
Support for Jetson Xavier NX

### ISSUE THREAD

**Issue by kumurule** [galliot-us/PifPaf-TensorRT-Pose-Estimation#1]
I tried to implement this model on Jetson xavier NX but it doesn't work..Are there any additional pre requisites needed.I have torch,tensorrt,pycuda,openpifpaf installed on jetson Xavier..Is there any other way to run this without using docker as its difficult to debug with docker

**Comment by cwlinghk** [comment]
I am able to run it on Jetson AGX.

**Comment by AnikaLiu628** [comment]
I can run on Jetson NX.

**Comment by NoLoPhe** [comment]
@cwlinghk and @AnikaLiu628  How did you run on Xavier nx?

![image](https://user-images.githubusercontent.com/60751518/140638266-bd04629d-a792-4fbc-8ffa-1603ee00bd83.png)

I'm building docker and got two error 

1. tensorflow==2.1.0' returned a non-zero code: 

2. ERROR: No matching distribution found for scipy==1.4.1; python_version >= "3"

**Comment by NoLoPhe** [comment]
Also, in performance testing, I only got 7 fps at
InputSize = 321.193
TensorrtPrecision = 16
it's pretty low, I hope >20fps

**Comment by gtierrezandres** [comment]
@NoLoPhe I'm also facing the same issue when building the Docker image. Were you able to find a solution?

**Comment by BigJoon** [comment]
@NoLoPhe Same issue with 
`I'm building docker and got two error

tensorflow==2.1.0' returned a non-zero code:

ERROR: No matching distribution found for scipy==1.4.1; python_version >= "3"`

Anyone find solution?
