### ISSUE TITLE
Not able to run inteference.py

### ISSUE THREAD

**Issue by ghost** [galliot-us/PifPaf-TensorRT-Pose-Estimation#3]
Hi, when I run the code, it raise me this error. May I know what's the problem?
![1](https://user-images.githubusercontent.com/52826239/113573427-bac3b100-964c-11eb-9c99-87d2f927616e.png)

**Comment by thancaocuong** [comment]
@hansheng0512  This error indicates that you convert model and run it on difference machines. So please convert and run inference on single machine.

**Comment by ghost** [comment]
Noted, the problem solved! May I know where I can get more pretrained model other than 2 that mentioned in blog?

**Comment by thancaocuong** [comment]
It has published on openpifpaf official. You can download these models [here](https://github.com/vita-epfl/openpifpaf-torchhub/releases/tag/v0.12.6)

**Comment by cwlinghk** [comment]
> It has published on openpifpaf official. You can download these models [here](https://github.com/vita-epfl/openpifpaf-torchhub/releases/tag/v0.12.6)

May anyone explain more on using the .pkl files?
How do I convert it to onnx file? thanks
