### ISSUE TITLE
how to get cif_meta.pkl and caf_meta.pkl

### ISSUE THREAD

**Issue by jagdishbhanushali** [galliot-us/PifPaf-TensorRT-Pose-Estimation#6]
Hello,
Great work for creating scripts and helping to generate. Recently openpifpaf have release v0.13.0. I am trying to get this thing working using tensorrt, but seems like I have to generate cif, caf metas. Could you please tell, how you got those metas.

Thank you,
Jagdish Bhanushali

**Comment by ledinhtri97** [comment]
+1

**Comment by thancaocuong** [comment]
@jagdishbhanushali you can generate it by loading the dataset and then save them as pkl files. You can find them in cocokp.py inside the plugins/coco directory.
