### ISSUE TITLE
Decode too slow

### ISSUE THREAD

**Issue by kongyanye** [galliot-us/PifPaf-TensorRT-Pose-Estimation#7]
In the article, the posted time for decoding is 8ms on server (with RTX 2070), but on my server the decoding time is about 22ms, much slower than the time reported. What's the decoding time you've tested?

![image](https://user-images.githubusercontent.com/11134804/144840049-d0b51a68-c5e6-4295-bfc3-661e2f9f300f.png)

**Comment by RTae** [comment]
@kongyanye How did you run this repo ? I run it with test data and didn't get result from it.
