### ISSUE TITLE
Test inference from example data,but does't get anything

### ISSUE THREAD

**Issue by RTae** [galliot-us/PifPaf-TensorRT-Pose-Estimation#8]
I convert onnx model to tensorrt by using model openpifpaf_resnet50_641_369 with precision 16 or 32 and the result is not thing

**Comment by agrija9** [comment]
Same for the other input size, I converted openpifpaf_resnet50_321_193_d16 from onnx to tensorrt but not getting any keypoints detected.

**Comment by RTae** [comment]
@agrija9 I got another solution.You can use onnx file of this repository with onnxruntime and  config onnxruntime as tensorrt, It work perfectly.

**Comment by agrija9** [comment]
Thanks for the heads-up. Is there any reference you could provide to check this?

**Comment by RTae** [comment]
https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html
