### ISSUE TITLE
How did you convert openpifpaf into the onnx model？

### ISSUE THREAD

**Issue by TimVerion** [galliot-us/PifPaf-TensorRT-Pose-Estimation#9]
I saw through openPifPaf's official website that they have some lightweight models, and I would like to ask you and translate these into ONNX for reasoning.
Such as:http://github.com/vita-epfl/openpifpaf-torchhub/releases/download/v0.11.0/shufflenetv2k16w-200510-221334-cif-caf-caf25-o10s-604c5956.pkl

**Comment by agrija9** [comment]
@TimVerion You can use the ``export_onnx.py`` that comes with OpenPifPaf, have a look at the script to see allowed arguments to generate the onnx model. 

An example to generate/download **shufflenet2x16** would be:

```
python3 -m openpifpaf.export_onnx --input-width 129 --input-height 97 --checkpoint tshufflenetv2k16 --outfile tshufflenetv2k16.onnx
```
